dataset:
  global_sampling_rate: null
  global_chunk_size: null
  modality_config:
    screen:
      keep_nans: false
      sampling_rate: 30
      chunk_size: 60
      valid_condition:
        tier: train
      offset: 0
      sample_stride: 1 # might be 60 
      include_blanks: true
      transforms:
        normalization: 
          means: 113
          stds: 59
      interpolation:
        rescale: false
    responses:
      keep_nans: false
      sampling_rate: 30
      chunk_size: 60
      offset: 0
      transforms:
        normalization: standardize
      interpolation:
        interpolation_mode: nearest_neighbor
    eye_tracker:
      keep_nans: false
      sampling_rate: 20
      chunk_size: 40
      offset: 0
      transforms:
        normalization: normalize
      interpolation:
        interpolation_mode: nearest_neighbor
      filters:
        nan_filter:
          __target__: experanto.filters.common_filters.nan_filter
          __partial__: True
          vicinity: 0.05
    treadmill:
      keep_nans: false
      sampling_rate: 20
      chunk_size: 40
      offset: 0
      transforms:
        normalization: normalize
      interpolation:
        interpolation_mode: nearest_neighbor
      filters:
        nan_filter:
          __target__: experanto.filters.common_filters.nan_filter
          __partial__: True
          vicinity: 0.05
dataloader:
  batch_size: 64
  shuffle: true
  num_workers: 2
  pin_memory: true
  drop_last: true
  prefetch_factor: 2
  shuffle_each_epoch: true
