training:
  batch_size: 8
  epochs: 250
  shuffle: True

data:
  paths: 
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic21067-10-18-Video-512cdd91f251cf74fff81375926f4002_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic22846-10-16-Video-512cdd91f251cf74fff81375926f4002_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic23343-5-17-Video-512cdd91f251cf74fff81375926f4002_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic23656-14-22-Video-512cdd91f251cf74fff81375926f4002_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic23964-4-22-Video-512cdd91f251cf74fff81375926f4002_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29156-11-10-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29228-2-10-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29234-6-9-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29513-3-5-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29514-2-9-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic26872-17-20-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29623-4-9-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29755-2-8-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic27204-5-13-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29647-19-8-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
    - /mnt/vast-react/projects/neural_foundation_model/Neuroformer_data_format/30Hz/dynamic29712-5-9-Video-021a75e56847d574b9acbcc06c675055_30hz.pkl
  scans: 
    - dynamic21067-10-18-Video-512cdd91f251cf74fff81375926f4002_30hz
    - dynamic22846-10-16-Video-512cdd91f251cf74fff81375926f4002_30hz
    - dynamic23343-5-17-Video-512cdd91f251cf74fff81375926f4002_30hz
    - dynamic23656-14-22-Video-512cdd91f251cf74fff81375926f4002_30hz
    - dynamic23964-4-22-Video-512cdd91f251cf74fff81375926f4002_30hz
    - dynamic29156-11-10-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic29228-2-10-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic29234-6-9-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic29513-3-5-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic29514-2-9-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic26872-17-20-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic29623-4-9-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic29755-2-8-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic27204-5-13-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic29647-19-8-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic29515-10-12-Video-021a75e56847d574b9acbcc06c675055_30hz
    - dynamic29712-5-9-Video-021a75e56847d574b9acbcc06c675055_30hz

dropout:
  attn: 0.2
  embd: 0.2
  pos: 0.2
  resid: 0.2
  temp: 0.2
  b: 0.2
  id: 0.2
  im: 0.2

block_size:
  behavior: 15
  frame: 60
  id: 16
  prev_id: 32

layers:
  state_history: 6
  state: 6
  stimulus: 6
  behavior: 6
  self_att: 6
  modalities:
    n_behavior: 25

sparse:
  p: null
  mask: false
  topk: null
  topk_frame: null
  topk_id: null
  topk_prev_id: null

window:
  frame: 2.0
  curr: 2.0
  prev: 4.0
  treadmill: 2.0  # Adding this allows for loss being calculated for all modalities and adds modalities to the target
  dillation: 2.0
  d_dilation: 2.0
  pupil_x: 2.0
  pupil_y: 2.0

# modality-specific parameters
modalities:
  behavior:
    n_layers: 4
    variables: 
      dilation:
        data: dilation
        dt: 0.05
        objective: regression
        predict: true
      d_dilation:
        data: d_dilation
        dt: 0.05
        objective: regression
        predict: true
      pupil_x:
        data: pupil_x
        dt: 0.05
        objective: regression
        predict: true
      pupil_y:
        data: pupil_y
        dt: 0.05
        objective: regression
        predict: true
      treadmill:
        data: treadmill
        dt: 0.05
        objective: regression
        predict: true
    window: 2.0

predict: null

frame_encoder:
  conv_layer: true
  kernel_size: [3, 8, 8]
  stride_size: [3, 4, 4]
  n_embd: 256
  n_embd_frames: 64
  resnet_backbone: false

contrastive:
  contrastive: false
  vars: ['id', 'frames']
  clip_embd: 1024
  clip_temp: 0.5

# resolution for predictions
resolution:
  dt: 0.0333333333333333
  frames: 0.03333333333333333

# GRU, MLP experiments
mlp_only: false
gru_only: false
gru2_only: false

# Rest of your parameters
class_weights: null
freeze_weights: null
n_head: 8
epoch: 0
n_embd: 256
pos_emb: true
pretrain: false
temp_emb: true
vit_encoder: true
ingore_index_pad: true

# selection of the data
selection: sel1